### ISSUE TITLE
I am trying to get this working but i keep in getting an error.

### ISSUE THREAD

**Issue by DAVE4547** [reboxer/discord-oauth2#18]
Whenever I try and start index.js it send this error message:
`(node:35704) UnhandledPromiseRejectionWarning: DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token
    at OAuth.request (D:\All projects\JS\Discord OAuth2 Test\NPM\node_modules\discord-oauth2\lib\eris\rest\RequestHandler.js:67:9)
    at OAuth.tokenRequest (D:\All projects\JS\Discord OAuth2 Test\NPM\node_modules\discord-oauth2\lib\oauth.js:83:15)
    at Object.<anonymous> (D:\All projects\JS\Discord OAuth2 Test\NPM\index.js:4:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
(node:35704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I am guessing that it is something either I haven't done properly or I haven't done at all.
Just to confirm I have inserted my own client id and client secret.

**Comment by DAVE4547** [comment]
found my problem

**Comment by WickedWizard3588** [comment]
@DAVE4547 Please share what happened, even I'm getting the same error. Thx

**Comment by DAVE4547** [comment]
@WickedWizard3588 sorry this was like 9 months ago and I can't remember what I had done to fix this.

**Comment by WickedWizard3588** [comment]
Ok, thx :)
