### ISSUE TITLE
DiscordHTTPError: 401 Unauthorized on GET /api/v7/users/@me on getUser() 

### ISSUE THREAD

**Issue by XMadFoX** [reboxer/discord-oauth2#28]
Well, after permission granted, I'm doing oauth.getUser(with token ofc) and catching this error
```
DiscordHTTPError: 401 Unauthorized on GET /api/v7/users/@me
    at OAuth.request (projectPath\node_modules\discord-oauth2\lib\eris\rest\RequestHandler.js:85:9)
    at OAuth.getUser (projectPath\node_modules\discord-oauth2\lib\oauth.js:114:15)
    at projectPath\src\index.js:35:11
    at Layer.handle [as handle_request] (projectPath\node_modules\express\lib\router\layer.js:95:5)
    at next (projectPath\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (projectPath\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (projectPath\node_modules\express\lib\router\layer.js:95:5)
    at projectPath\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (projectPath\node_modules\express\lib\router\index.js:335:12)
    at next (projectPath\node_modules\express\lib\router\index.js:275:10)
```
I didn't find a solution here https://github.com/reboxer/discord-oauth2/issues/26
P.S. In Authorized apps tab, app have permission to identify

**Comment by reboxer** [comment]
Please provide the code you are using, it's impossible for me to guess what's wrong if i can't see what you are doing.

**Comment by XMadFoX** [comment]
```js
const DiscordOauth2 = require('discord-oauth2');
const oauth = new DiscordOauth2({
    clientId: "xxx",
    clientSecret: "xxx",
    redirectUri: "http://localhost:4001/auth/discord/callback",
});

const express = require('express');
const cookieParser = require('cookie-parser');
const app = express();
app.use(cookieParser());

app.get('/auth/discord/callback', (req, res) => {
    console.log(req.query.code); //Just debugging
    oauth.getUser(req.query.code).then(res => console.log(res)).catch(err => console.log(err))
    res.redirect("http://localhost:3000"); //Moving user to frontend
})

app.listen(4001,() => {...});
```

**Comment by reboxer** [comment]
The query code in the callback uri is not the token you use to request user data, you have to use `tokenRequest()` with the query code to get said token, and then you can use `getUser()`.

**Comment by XMadFoX** [comment]
Got it, thank you.
