### ISSUE TITLE
400 Bad Request on POST /api/v7/oauth2/token.

### ISSUE THREAD

**Issue by Pelfox** [reboxer/discord-oauth2#58]
**Describe the error**
When I try to get a new token for a user using your library, I get a **400 Bad Request** error.
Full log: 
```log
DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token
    at OAuth.request (/Users/julheer/Desktop/monobuild/node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js:85:9)
    at OAuth.tokenRequest (/Users/julheer/Desktop/monobuild/node_modules/discord-oauth2/lib/oauth.js:85:15)
    at /Users/julheer/Desktop/monobuild/src/modules/discord.js:25:11
    at Layer.handle [as handle_request] (/Users/julheer/Desktop/monobuild/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/julheer/Desktop/monobuild/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/julheer/Desktop/monobuild/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/julheer/Desktop/monobuild/node_modules/express/lib/router/layer.js:95:5)
    at /Users/julheer/Desktop/monobuild/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/julheer/Desktop/monobuild/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/julheer/Desktop/monobuild/node_modules/express/lib/router/index.js:275:10)
```

**NodeJS version**
*v15.5.0*, and dependencies:
```json
"dependencies": {
    "discord-oauth2": "^2.6.0",
    "dotenv": "^10.0.0",
    "express": "^4.17.1",
    "express-session": "^1.17.2",
    "monk": "^7.3.4",
    "nodemon": "^2.0.7",
    "uuid": "^8.3.2"
  }
```

**Relevant code**
```js
const Discord = require('discord-oauth2');
const oauth = new Discord({
    clientId: process.env.ID,
    clientSecret: process.env.SECRET,
    redirectUri: 'http://localhost:8000/discord/code'
});
...
oauth.tokenRequest({
        code: 'query code',
        scope: 'identify email',
        grantType: 'authorization_code',
    }).then(code => {
        console.log(code);
    });
```

**Comment by HKGx** [comment]
wasn't v7 skipped?

**Comment by Pelfox** [comment]
It’s skipped, but library continue work with this version

**Comment by reboxer** [comment]
Hey, sorry for taking so long.
It looks like your code is completely valid and works fine, in this case the `DiscordHTTPError: 400 Bad Request on POST` is very likely a wrong authorization code, you can confirm this by adding this `catch` block to the function call:

```js
oauth.tokenRequest({
        code: 'query code',
        scope: 'identify email',
        grantType: 'authorization_code',
    }).then(code => {
        console.log(code);
    })
    .catch((e) => {
        console.log(e.message)
        console.log(e.response)
    })
```
and it should return the following:

```js
DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token
{
  error: 'invalid_request',
  error_description: 'Invalid "code" in request.'
}
```

You are probably getting the authorization code wrong or the library/middlewares you are using are changing the string and making it invalid.
If that's not the case, please send the error here so we can see what's going on.

**Comment by Pelfox** [comment]
Fixed for me now. Sorry

**Comment by dragochar** [comment]
Am getting the same error. Have been going over it for a while and even inputting the 'code' string manually still gives 'Invalid "code" in request.'.

Not too sure what's going on.
