### ISSUE TITLE
Error When Getting Access Token

### ISSUE THREAD

**Issue by TheGoldenCactus11** [reboxer/discord-oauth2#7]
```
const express = require('express');
const path = require('path');

const app = express();

const DiscordOauth2 = require("discord-oauth2");
const oauth = new DiscordOauth2();

const fetch = require('node-fetch')

CLIENT_ID = '598419143661846528'

CLIENT_SECRET = process.env.secret
const redirect = encodeURIComponent('https://discord-Oauth2.rossjames.repl.co/auth')

app.get('/', (req, res) => {
  res.redirect(`https://discordapp.com/api/oauth2/authorize?client_id=${CLIENT_ID}&scope=identify&response_type=code&redirect_uri=${redirect}`);
});

app.get('/auth', async(req, res) => {
	oauth.tokenRequest({
			clientId: CLIENT_ID,
			clientSecret: CLIENT_SECRET,
	
			code: req.query.code,
			scope: "identify",
			grantType: "authorization_code",
			
			redirectUri: "https://discord-Oauth2.rossjames.repl.co"
	}).then(res.send)
});

app.listen(50451, () => {
  console.info('Running on port 50451');
});
```

Returns :
```(node:216) UnhandledPromiseRejectionWarning: DiscordHTTPError: 400 BAD REQUEST on POST /api/v7/oauth2/token
    at OAuth.request (/home/runner/node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js:90:15)
    at OAuth.tokenRequest (/home/runner/node_modules/discord-oauth2/lib/oauth.js:56:21)
    at app.get (/home/runner/index.js:21:8)
    at Layer.handle [as handle_request] (/home/runner/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/runner/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/runner/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/runner/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/node_modules/express/lib/router/index.js:275:10)
(node:216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by reboxer** [comment]
In your OAuth2 link you set your redirect uri to `https://discord-Oauth2.rossjames.repl.co/auth` but in the token request you set it to `https://discord-Oauth2.rossjames.repl.co`, these two have to be the exact same thing and also has to be enabled in the discord developers page.

**Comment by TheGoldenCactus11** [comment]
> In your OAuth2 link you set your redirect uri to `https://discord-Oauth2.rossjames.repl.co/auth` but in the token request you set it to `https://discord-Oauth2.rossjames.repl.co`, these two have to be the exact same thing (also has to be added in the discord developers page).

I have fixed it not by just making a manual request, although, at a later stage, I did have redirect Uri set to the variable redirect, if it was this problem, the error code was not specific enough. Thanks for your help tho
