### ISSUE TITLE
400 Bad Request when using addMember

### ISSUE THREAD

**Issue by willuhm-js** [reboxer/discord-oauth2#74]
**Describe the error**
Trying to get a user to join a guild. Get a 400 error.

**NodeJS version**
v16.X.X

**Library version**
latest

**Error stack and exact error message**
ode:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token
    at OAuth.request (/home/runner/Einfach-Servers/node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js:84:9)
    at OAuth.tokenRequest (/home/runner/Einfach-Servers/node_modules/discord-oauth2/lib/oauth.js:91:15)

**Relevant code**
```js
const user = await oauth.getUser(token);
  const guilds = await oauth.getUserGuilds(token);
  await oauth.addMember({
    accessToken: token,
    botToken: process.env.BOT_TOKEN,
    guildId: "...",
    userId: user.id
  });
```

**Comment by willuhm-js** [comment]
Solution found: The bot must be in the guild you are attempting to make users join, and it must have sufficient permissions in the guild.
