### ISSUE TITLE
DiscordHTTPError: 401 Unauthorized on POST /api/v9/oauth2/token

### ISSUE THREAD

**Issue by realpukhraj** [reboxer/discord-oauth2#75]
**NodeJS version**
v16

**Library version**
discord.js

**Error stack and exact error message**
DiscordHTTPError: 401 Unauthorized on POST /api/v9/oauth2/token
    at OAuth.request (/root/test/node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js:90:9)
    at OAuth.tokenRequest (/root/test/node_modules/discord-oauth2/lib/oauth.js:110:15)
    at /root/test/src/app/site.js:38:26
    at Layer.handle [as handle_request] (/root/test/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/test/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/test/node_modules/express/lib/router/layer.js:95:5)
    at /root/test/node_modules/express/lib/router/index.js:281:22
    at param (/root/test/node_modules/express/lib/router/index.js:360:14)
    at param (/root/test/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/root/test/node_modules/express/lib/router/index.js:416:3)
    at next (/root/test/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/root/test/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/root/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/test/node_modules/express/lib/router/index.js:323:13)
    at /root/test/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/test/node_modules/express/lib/router/index.js:341:12)
    at next (/root/test/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/root/test/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/root/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/test/node_modules/express/lib/router/index.js:323:13)
    at /root/test/node_modules/express/lib/router/index.js:284:7

**Relevant code**
```js
const DiscordOauth2 = require("discord-oauth2");
const oauth = new DiscordOauth2({
  version: "v9",
  clientId: settings.websitebot_client_id,
  clientSecret: settings.website.bot_client_secret,
  redirectUri: settings.website.callback,
});
let data = await oauth.tokenRequest({
    code: req.query.code,
    scope: "identify guilds email",
    grantType: "authorization_code",
    redirectUri: url,
  });
console.log(data)
```

**Comment by reboxer** [comment]
Sorry, you got the wrong repository, this is not discord.j so i can't help you. And you are not following the issue template either.
