### ISSUE TITLE
TypeError: Class extends value [object Object] is not a constructor or null

### ISSUE THREAD

**Issue by OyewoleOyedeji** [reboxer/discord-oauth2#81]
**Describe the error**
The library works normally on `Nuxt 3` development server but when I build the project for production it causes the project to crash. This is the logs
```
TypeError: Class extends value [object Object] is not a constructor or null

 at node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js (RequestHandler.js:35:1)
    at __require (chunk-TH2OHAGX.js?v=132c6beb:6:50)
    at node_modules/discord-oauth2/lib/oauth.js (oauth.js:3:24)
    at __require (chunk-TH2OHAGX.js?v=132c6beb:6:50)
    at node_modules/discord-oauth2/index.js (index.js:2:15)
    at __require (chunk-TH2OHAGX.js?v=132c6beb:6:50)
    at dep:discord-oauth2:1:16
```

This is the [link](https://discord-profiler-l8eddlb5m-oyedejioyewole.vercel.app/) to the deployed project as proof. Please don't close this issue

**NodeJS version**
*v16.16.0*

**Library version**
*^2.10.0*

**Error stack and exact error message**
```
TypeError: Class extends value [object Object] is not a constructor or null

 at node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js (RequestHandler.js:35:1)
    at __require (chunk-TH2OHAGX.js?v=132c6beb:6:50)
    at node_modules/discord-oauth2/lib/oauth.js (oauth.js:3:24)
    at __require (chunk-TH2OHAGX.js?v=132c6beb:6:50)
    at node_modules/discord-oauth2/index.js (index.js:2:15)
    at __require (chunk-TH2OHAGX.js?v=132c6beb:6:50)
    at dep:discord-oauth2:1:16
```

**Relevant code**
```js
import DiscordOAuth from 'discord-oauth2';

const oauth = new DiscordOAuth()
```

This is all that is need to break the server on production environment, please help 🙏🏼

**Comment by reboxer** [comment]
Not a library issue. This has something to do with how Nuxt compiles the code,

**Comment by OyewoleOyedeji** [comment]
@reboxer but it works on the server route, not just on the client route

**Comment by reboxer** [comment]
As i said, not a library issue, this is Nuxt's fault.
