### ISSUE TITLE
TypeError: discord_oauth2_1.default is not a constructor

### ISSUE THREAD

**Issue by larky0071** [reboxer/discord-oauth2#82]
NodeJS: 18.9.0
discord-oauth2: ^2.10.0

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2022",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

TypeError: discord_oauth2_1.default is not a constructor
    at DiscordService.getAccessToken (C:\Users\Larky\Documents\GitHub\part-of-good-backend\src\discord\discord.service.ts:10:23)
    at AuthenticationController.testRoute (C:\Users\Larky\Documents\GitHub\part-of-good-backend\src\authentication\authentication.controller.ts:26:48)
    at C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\@nestjs\core\router\router-execution-context.js:38:29
    at InterceptorsConsumer.transformDeferred (C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\@nestjs\core\interceptors\interceptors-consumer.js:31:33)
    at C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\@nestjs\core\interceptors\interceptors-consumer.js:15:53
    at Observable._subscribe (C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\rxjs\src\internal\observable\defer.ts:55:15)
    at Observable._trySubscribe (C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\rxjs\src\internal\Observable.ts:245:19)
    at C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\rxjs\src\internal\Observable.ts:235:18
    at Object.errorContext (C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
    at Observable.subscribe (C:\Users\Larky\Documents\GitHub\part-of-good-backend\node_modules\rxjs\src\internal\Observable.ts:221:5)
    ![Code_r4jlre0NvQ](https://user-images.githubusercontent.com/56645515/191438606-a3e4dff0-23c4-4bf7-be9b-d86ae9990935.png)

**Comment by reboxer** [comment]
Same as #81
