### ISSUE TITLE
typeError: Class extends value [object Object] is not a constructor or null

### ISSUE THREAD

**Issue by zuifiti** [reboxer/discord-oauth2#86]
**Describe the error**
typeError: Class extends value [object Object] is not a constructor or null

**NodeJS version**
16.13.2

**Library version**
2.10.1

**Error stack and exact error message**
TypeError: Class extends value [object Object] is not a constructor or null
    at node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js (RequestHandler.js:35:1)
    at __require (chunk-J43GMYXM.js?v=ae090979:11:50)
    at node_modules/discord-oauth2/lib/oauth.js (oauth.js:3:24)
    at __require (chunk-J43GMYXM.js?v=ae090979:11:50)
    at node_modules/discord-oauth2/index.js (index.js:2:15)
    at __require (chunk-J43GMYXM.js?v=ae090979:11:50)
    at dep:discord-oauth2:1:16

**Relevant code**
```js
import DiscordOauth2 from "discord-oauth2";
const oauth = new DiscordOauth2();
```
I'm using react (vite in devlopment mode).

**Comment by reboxer** [comment]
This library is meant for use in NodeJS, not in a browser.
