### ISSUE TITLE
DiscordHTTPError: 400 Bad Request on POST /api/v9/oauth2/token

### ISSUE THREAD

**Issue by zuifiti** [reboxer/discord-oauth2#87]
**Describe the error**
This error is occurring when I use tokenRequest() 

**NodeJS version**
*16.15.0*

**Library version**
*2.10.1*

**Error stack and exact error message**
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DiscordHTTPError: 400 Bad Request on POST /api/v9/oauth2/token
    at OAuth.request (/home/runner/uriel/node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js:90:9)
    at OAuth.tokenRequest (/home/runner/uriel/node_modules/discord-oauth2/lib/oauth.js:110:15)
    at file:///home/runner/uriel/src/dashboard/index.js:78:9
    at Layer.handle [as handle_request] (/home/runner/uriel/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/uriel/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/uriel/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/uriel/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/uriel/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/uriel/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/uriel/node_modules/express/lib/router/index.js:280:10)

**Relevant code**
```js
app.get("/tokenrequest", async (req, res) => {
  const requestcode = req.headers["x-req-code"]; // is returning my "code" provided by the discord api (I checked)
  
  oauth.tokenRequest({
	clientId: process.env.BOT_ID, 
	clientSecret: process.env.CLIENT_SECRET,
	code: requestcode,
	grantType: "authorization_code",

	redirectUri: "https://mysite.exemple.com",
}).then(console.log)
})    
```

**Comment by reboxer** [comment]
Just like @Axure0 said, the code is added by discord as a URL query parameter and not as a request header.

**Comment by zuifiti** [comment]
> 

well i made my own interaction with discord without using package and it worked

**Comment by zuifiti** [comment]
> > 
> 
> well i made my own interaction with discord without using this package and it worked

**Comment by Axure0** [comment]
Well, maybe the discord api uses headers but this package uses a query parameter.

**Comment by reboxer** [comment]
> but this package uses a query parameter.
because that's the only thing discord uses for OAuth2 and it's the only way to do it. No idea where this `x-req-code` comes from as it's not mentioned anywhere in the entire API documentation.
